In [5]:
import numpy as np
from scipy.linalg import svd

# define a matrix
A = np.array([[1, 0, 0, 0, 2], 
           [0, 0, 3, 0, 0], 
           [0, 0, 0, 0, 0],
           [0, 2, 0, 0, 0]])
print("Original:")
print(A)

# SVD
U, E, Vt = svd(A)
D = np.zeros((A.shape[0], A.shape[1]))
D[:A.shape[1], :A.shape[0]] = np.diag(E)
UDVt = U.dot(D).dot(Vt)

print("Reconstructed:")
print(UDVt)

Original:
[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 2 0 0 0]]
Reconstructed:
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]
